on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string
      tag_name:
        required: true
        type: string


jobs:
  test-1:
    runs-on: ubuntu-latest
    steps:
      - name: t1
        run: |
          echo ${{ inputs.environment }}
          echo ${{ inputs.tag_name }}
          echo ${{ github.event_name }}
          echo "abc"

