name: Build push and deylopment

on:
  workflow_dispatch:

jobs:
  Build_and_Push:
    uses: ./.github/workflows/a1.yaml


  Deployment:
    needs: call-workflow-in-local-repo
    uses: ./.github/workflows/a2.yaml
