name: Build push and deylopment

on:
  workflow_dispatch:

jobs:
  Build_and_Push:
    uses: ./.github/workflows/a1.yaml


  Deployment:
    needs: Build_and_Push
    uses: ./.github/workflows/a2.yaml
