name: C/C++ CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: make
      run: make

    - name: Prepare artifact
      run: |
          mkdir -p ./artifact/bin
          cp ./demo ./artifact/bin/

    - name: Upload buildinfo
      uses: actions/upload-artifact@v3
      with:
        name: demo_buildinfo
        path: ./artifact/bin/

