name: Call a reusable workflow and use its outputs

on:
  workflow_dispatch:
    inputs:
      environment:
        description: "Environment on which to deploy (dev|staging|prod)"
        type: choice
        required: false
        options:
          - dev
          - staging
          - prod

      tag_name:
        description: "Project tag name"
        type: string
        required: true
        default: 'latest'


jobs:
  call-workflow-in-local-repo:
    uses: ./.github/workflows/a1.yaml
    with:
      environment: "rty"
      tag_name: "tag_name"


  call-workflow-in-local-repo-2:
    needs: call-workflow-in-local-repo
    uses: ./.github/workflows/a2.yaml
