name: Main Workflow
on:
  workflow_dispatch:

jobs:
  call_1:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Call First Workflow
        uses: ./a1.yaml  # 引用第一个自定义YAML文件中的工作流定义


  call_2:
    needs: call_1
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Call Second Workflow
        uses: ./a2.yaml  # 引用第二个自定义YAML文件中的工作流定义

