name: Call a reusable workflow and use its outputs

on:
  workflow_dispatch:

jobs:
  call-workflow-in-local-repo:
    uses: ./.github/workflows/a1.yaml


  call-workflow-in-local-repo-2:
    uses: ./.github/workflows/a2.yaml
