name: Main Workflow-2
on:
  workflow_dispatch:

jobs:
  call_1:
    uses: ./.github/workflows/a1.yaml@master  # 引用第一个自定义YAML文件中的工作流定义
#    runs-on: ubuntu-latest
#    steps:
#      - name: Checkout code
#        uses: actions/checkout@v4
#      
#      - name: Call First Workflow
#        uses: ./.github/workflows/a1.yaml@master  # 引用第一个自定义YAML文件中的工作流定义


  call_2:
    needs: call_1
      uses: ./.github/workflows/a2.yaml@master  # 引用第一个自定义YAML文件中的工作流定义
#    runs-on: ubuntu-latest
#    steps:
#      - name: Checkout code
#        uses: actions/checkout@v4
#      
#      - name: Call Second Workflow
#        uses: ./.github/workflows/a2.yaml@master  # 引用第一个自定义YAML文件中的工作流定义

