name: Call Another Workflow

on:
  workflow_dispatch:

jobs:
  call-other-workflow:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Call the other workflow
        uses: actions/workflow-dispatch@v1
        with:
          workflow: './a1.yml'  # 指定你的另一个工作流程文件的路径
          input_username: 'custom-username'  # 传递自定义的用户名作为参数

